<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC1490" name="com.dts.adminportal.dts.test.DTSProducts051DProductEdit" tests="37" failures="0" timestamp="18 Mar 2018 17:57:25 GMT" time="4331.439" errors="6">
  <testcase name="TC051DAE_25" time="34.808" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit">
    <error type="java.lang.RuntimeException" message="Image file can not be loaded from C:\Users\anh.dinh\Desktop\Automation\DTS-Portal-Automation-New\asset\target\Tuning.png">
      <![CDATA[java.lang.RuntimeException: Image file can not be loaded from C:\Users\anh.dinh\Desktop\Automation\DTS-Portal-Automation-New\asset\target\Tuning.png
	at org.sikuli.api.ImageTarget.<init>(ImageTarget.java:65)
	at com.dts.adminportal.controller.BaseController.dragDropFile(BaseController.java:1549)
	at com.dts.adminportal.dts.test.DTSProducts051DProductEdit.TC051DAE_25(DTSProducts051DProductEdit.java:820)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- TC051DAE_25 -->
  <testcase name="TC051DAE_81" time="106.839" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_76" time="121.430" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_41" time="141.853" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_75" time="46.459" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_99" time="92.419" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_106" time="214.067" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_55" time="54.394" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_01" time="35.804" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_64" time="59.008" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_105" time="207.076" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_20" time="173.729" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_103" time="45.877" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit">
    <error type="java.lang.RuntimeException" message="Image file can not be loaded from C:\Users\anh.dinh\Desktop\Automation\DTS-Portal-Automation-New\asset\imageSave.PNG">
      <![CDATA[java.lang.RuntimeException: Image file can not be loaded from C:\Users\anh.dinh\Desktop\Automation\DTS-Portal-Automation-New\asset\imageSave.PNG
	at org.sikuli.api.ImageTarget.<init>(ImageTarget.java:65)
	at com.dts.adminportal.controller.ProductController.clickSaveLinkWhileUploading(ProductController.java:525)
	at com.dts.adminportal.dts.test.DTSProducts051DProductEdit.TC051DAE_103(DTSProducts051DProductEdit.java:2618)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- TC051DAE_103 -->
  <testcase name="TC051DAE_77" time="68.330" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_67" time="70.367" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_47" time="145.989" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_35" time="77.047" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_101" time="151.401" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_104" time="37.966" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_69" time="220.838" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_96" time="58.900" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_85" time="137.641" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_66" time="53.007" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_44" time="167.321" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_46" time="180.790" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_11" time="57.756" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_27" time="45.824" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_10" time="146.645" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_87" time="45.609" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dts.adminportal.controller.ProductController.clickImage(ProductController.java:508)
	at com.dts.adminportal.dts.test.DTSProducts051DProductEdit.TC051DAE_87(DTSProducts051DProductEdit.java:2033)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- TC051DAE_87 -->
  <testcase name="TC051DAE_89" time="54.165" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_03" time="227.103" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_100" time="265.041" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_98" time="70.078" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dts.adminportal.controller.ProductController.clickImage(ProductController.java:508)
	at com.dts.adminportal.dts.test.DTSProducts051DProductEdit.TC051DAE_98(DTSProducts051DProductEdit.java:2201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- TC051DAE_98 -->
  <testcase name="TC051DAE_39" time="58.954" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit">
    <error type="java.lang.RuntimeException" message="Image file can not be loaded from C:\Users\anh.dinh\Desktop\Automation\DTS-Portal-Automation-New\asset\target\Tuning.png">
      <![CDATA[java.lang.RuntimeException: Image file can not be loaded from C:\Users\anh.dinh\Desktop\Automation\DTS-Portal-Automation-New\asset\target\Tuning.png
	at org.sikuli.api.ImageTarget.<init>(ImageTarget.java:65)
	at com.dts.adminportal.controller.BaseController.dragDropFile(BaseController.java:1549)
	at com.dts.adminportal.dts.test.DTSProducts051DProductEdit.TC051DAE_39(DTSProducts051DProductEdit.java:980)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- TC051DAE_39 -->
  <testcase name="TC051DAE_102" time="37.255" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit">
    <error type="java.lang.RuntimeException" message="Image file can not be loaded from C:\Users\anh.dinh\Desktop\Automation\DTS-Portal-Automation-New\asset\imageSave.PNG">
      <![CDATA[java.lang.RuntimeException: Image file can not be loaded from C:\Users\anh.dinh\Desktop\Automation\DTS-Portal-Automation-New\asset\imageSave.PNG
	at org.sikuli.api.ImageTarget.<init>(ImageTarget.java:65)
	at com.dts.adminportal.controller.ProductController.clickSaveLinkWhileUploading(ProductController.java:525)
	at com.dts.adminportal.dts.test.DTSProducts051DProductEdit.TC051DAE_102(DTSProducts051DProductEdit.java:2557)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- TC051DAE_102 -->
  <testcase name="TC051DAE_107" time="77.365" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
  <testcase name="TC051DAE_05" time="542.284" classname="com.dts.adminportal.dts.test.DTSProducts051DProductEdit"/>
</testsuite> <!-- com.dts.adminportal.dts.test.DTSProducts051DProductEdit -->
